/*.$file${.::event_def.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: button.qm
* File:  ${.::event_def.h}
*
* This code has been generated by QM 5.1.4 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${.::event_def.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef EVENT_DEF_H
#define EVENT_DEF_H

#include "qpc.h"

enum
{
    Event_Test = Q_USER_SIG,
    Evt_Button,
    ButtonClick_SIG,
    ButtonDoubleClick_SIG,
    ButtonLongPress_SIG,

    MAX_PUB_SIG,

    Evt_Led1_OnOff,
    Evt_Led2_OnOff,
    Evt_Led3_OnOff,
    Evt_Led4_OnOff,

    ButtonPoll_SIG,
    TimeCount_SIG,
    ButtonPressed_SIG,
    ButtonReleased_SIG,



    MAX_SIG
};

typedef struct m_evt_tag {
    QEvt super;
    uint32_t data;
} m_evt_t;

#endif
