/*.$file${.::sm_count.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: button.qm
* File:  ${.::sm_count.c}
*
* This code has been generated by QM 5.1.4 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${.::sm_count.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "sm_count.h"
#include "event_def.h"
#include "sm_def.h"

Q_DEFINE_THIS_MODULE("SmCount")

/*.$declare${sm::sm_count} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${sm::sm_count} .........................................................*/
typedef struct {
/* protected: */
    QActive super;

/* public: */
    uint32_t count_click;
    uint32_t count_double_click;
    uint32_t count_long_press;
} sm_count;

/* public: */
static void sm_count_sm_count_init(sm_count * const me);

/* protected: */
static QState sm_count_initial(sm_count * const me, void const * const par);
static QState sm_count_work(sm_count * const me, QEvt const * const e);
/*.$enddecl${sm::sm_count} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

sm_count count;
void sm_count_init(void)
{
    sm_count_sm_count_init(&count);
}

/*.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*. Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.9.0 or higher required
#endif
/*.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${sm::sm_count} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${sm::sm_count} .........................................................*/
/*.${sm::sm_count::sm_count_init} ..........................................*/
static void sm_count_sm_count_init(sm_count * const me) {
    // 活动对象的构建
    QActive_ctor(&me->super, Q_STATE_CAST(&sm_count_initial));
    // 活动对象的启动
    static QEvt const *equeue[SM_COUNT_QUEUE_LENGTH];
    QACTIVE_START(&me->super,
                  SmPrio_Count,
                  equeue, SM_COUNT_QUEUE_LENGTH,
                  (void *)0, 0U,
                  (void *)0);
}

/*.${sm::sm_count::SM} .....................................................*/
static QState sm_count_initial(sm_count * const me, void const * const par) {
    /*.${sm::sm_count::SM::initial} */
    return Q_TRAN(&sm_count_work);
}
/*.${sm::sm_count::SM::work} ...............................................*/
static QState sm_count_work(sm_count * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${sm::sm_count::SM::work} */
        case Q_ENTRY_SIG: {
            QActive_subscribe(&me->super, ButtonClick_SIG);
            QActive_subscribe(&me->super, ButtonDoubleClick_SIG);
            QActive_subscribe(&me->super, ButtonLongPress_SIG);
            status_ = Q_HANDLED();
            break;
        }
        /*.${sm::sm_count::SM::work::ButtonClick} */
        case ButtonClick_SIG: {
            me->count_click ++;
            status_ = Q_HANDLED();
            break;
        }
        /*.${sm::sm_count::SM::work::ButtonDoubleClick} */
        case ButtonDoubleClick_SIG: {
            me->count_double_click ++;
            status_ = Q_HANDLED();
            break;
        }
        /*.${sm::sm_count::SM::work::ButtonLongPress} */
        case ButtonLongPress_SIG: {
            me->count_long_press ++;
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*.$enddef${sm::sm_count} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
