/*.$file${.::sm_led_qm.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: led.qm
* File:  ${.::sm_led_qm.c}
*
* This code has been generated by QM 5.1.4 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${.::sm_led_qm.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpc.h"
#include "led.h"
#include "event_def.h"
#include "sm_def.h"

Q_DEFINE_THIS_MODULE("SmLed")

/*.$declare${SMs::sm_led_t} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${SMs::sm_led_t} ........................................................*/
typedef struct {
/* protected: */
    QActive super;

/* public: */
    bool status;
} sm_led_t;

/* protected: */
static QState sm_led_t_initial(sm_led_t * const me, void const * const par);
static QState sm_led_t_off(sm_led_t * const me, QEvt const * const e);
static QState sm_led_t_on(sm_led_t * const me, QEvt const * const e);
/*.$enddecl${SMs::sm_led_t} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

static sm_led_t sm_led;

void sm_led_init(void)
{
    sm_led_t *me = &sm_led;

    // 活动对象的构建
    QActive_ctor(&me->super, Q_STATE_CAST(&sm_led_t_initial));
    // 活动对象的启动
    static QEvt const *e_queue[SM_LED_QUEUE_LENGTH];
    QACTIVE_START(&me->super,
                  SmPrio_Led,
                  e_queue, SM_LED_QUEUE_LENGTH,
                  (void *)0, 0U,
                  (void *)0);
}

/*.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*. Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.9.0 or higher required
#endif
/*.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${SMs::sm_led_t} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${SMs::sm_led_t} ........................................................*/
/*.${SMs::sm_led_t::SM} ....................................................*/
static QState sm_led_t_initial(sm_led_t * const me, void const * const par) {
    /*.${SMs::sm_led_t::SM::initial} */
    // 事件的订阅
    QActive_subscribe(&me->super, Evt_LedOnOff_SIG);
    return Q_TRAN(&sm_led_t_off);
}
/*.${SMs::sm_led_t::SM::off} ...............................................*/
static QState sm_led_t_off(sm_led_t * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${SMs::sm_led_t::SM::off} */
        case Q_ENTRY_SIG: {
            // 关闭LED灯
            led_set_status(Device_Led1, false);
            led_set_status(Device_Led2, false);
            led_set_status(Device_Led3, false);
            led_set_status(Device_Led4, false);
            status_ = Q_HANDLED();
            break;
        }
        /*.${SMs::sm_led_t::SM::off::Evt_LedOnOff} */
        case Evt_LedOnOff_SIG: {
            status_ = Q_TRAN(&sm_led_t_on);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*.${SMs::sm_led_t::SM::on} ................................................*/
static QState sm_led_t_on(sm_led_t * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${SMs::sm_led_t::SM::on} */
        case Q_ENTRY_SIG: {
            // 打开LED灯
            led_set_status(Device_Led1, true);
            led_set_status(Device_Led2, true);
            led_set_status(Device_Led3, true);
            led_set_status(Device_Led4, true);
            status_ = Q_HANDLED();
            break;
        }
        /*.${SMs::sm_led_t::SM::on::Evt_LedOnOff} */
        case Evt_LedOnOff_SIG: {
            status_ = Q_TRAN(&sm_led_t_off);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*.$enddef${SMs::sm_led_t} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
